# use my hacked up gem locally
theme: minima
# use my hacked up version on github
# remote_theme: DavidS/time-machine
show_downloads: false

url: 'https://club.black.co.at'
baseurl: '/log'
title: "DavidS' log"
author: 'David Schmitt'

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  collections:
    posts:
      categories:
        - puppet

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # this pattern matches up with previous' ikiwiki URLs for the blog
      permalink: /posts/:year-:month-:day-:title/index:output_ext

jekyll_analytics:
  GoogleAnalytics:
    id: UA-155086367-1
    anonymizeIp: true
